/********************************************************************
* anacore_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error anacore_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableanacore_dict();
extern void G__cpp_setup_inheritanceanacore_dict();
extern void G__cpp_setup_typetableanacore_dict();
extern void G__cpp_setup_memvaranacore_dict();
extern void G__cpp_setup_globalanacore_dict();
extern void G__cpp_setup_memfuncanacore_dict();
extern void G__cpp_setup_funcanacore_dict();
extern void G__set_cpp_environmentanacore_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/segidlist.hh"
#include "include/TArtConfig.hh"
#include "include/TArtCore.hh"
#include "include/TArtDataObject.hh"
#include "include/TArtDataSource.hh"
#include "include/TArtDecoderA3100.hh"
#include "include/TArtDecoderAD413A.hh"
#include "include/TArtDecoderAMTTDC.hh"
#include "include/TArtDecoderCBLT.hh"
#include "include/TArtDecoderCTM405.hh"
#include "include/TArtDecoderDSP.hh"
#include "include/TArtDecoderFactory.hh"
#include "include/TArtDecoderFixed16.hh"
#include "include/TArtDecoderFixed24.hh"
#include "include/TArtDecoderFixed32.hh"
#include "include/TArtDecoder.hh"
#include "include/TArtDecoderL3377d.hh"
#include "include/TArtDecoderLUPO.hh"
#include "include/TArtDecoderMADC32.hh"
#include "include/TArtDecoderP716X.hh"
#include "include/TArtDecoderP716XZ.hh"
#include "include/TArtDecoderV1190C.hh"
#include "include/TArtDecoderV1190.hh"
#include "include/TArtDecoderV1290.hh"
#include "include/TArtDecoderV1740.hh"
#include "include/TArtDecoderV550.hh"
#include "include/TArtDecoderV767.hh"
#include "include/TArtDecoderV7XX.hh"
#include "include/TArtDecoderV830.hh"
#include "include/TArtEventInfo.hh"
#include "include/TArtEventStore.hh"
#include "include/TArtFileDataSource.hh"
#include "include/TArtMap.hh"
#include "include/TArtMath.hh"
#include "include/TArtParserFactory.hh"
#include "include/TArtParser.hh"
#include "include/TArtParserRDF.hh"
#include "include/TArtParserRIDF.hh"
#include "include/TArtRawDataObject.hh"
#include "include/TArtRawEventObject.hh"
#include "include/TArtRawFADCDataObject.hh"
#include "include/TArtRawScalerObject.hh"
#include "include/TArtRawSegmentObject.hh"
#include "include/TArtReconstruction.hh"
#include "include/TArtSemaphore.hh"
#include "include/TArtSharedMemoryDataSource.hh"
#include "include/TArtSharedMemory.hh"
#include "include/TArtStoreManager.hh"
#include "include/TArtStreamingDataSource.hh"
#include "include/TArtUtil.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__anacore_dictLN_TClass;
extern G__linked_taginfo G__anacore_dictLN_TBuffer;
extern G__linked_taginfo G__anacore_dictLN_TMemberInspector;
extern G__linked_taginfo G__anacore_dictLN_TObject;
extern G__linked_taginfo G__anacore_dictLN_TNamed;
extern G__linked_taginfo G__anacore_dictLN_TString;
extern G__linked_taginfo G__anacore_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__anacore_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anacore_dictLN_TList;
extern G__linked_taginfo G__anacore_dictLN_TClonesArray;
extern G__linked_taginfo G__anacore_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__anacore_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anacore_dictLN_TArtCore;
extern G__linked_taginfo G__anacore_dictLN_TArtDataObject;
extern G__linked_taginfo G__anacore_dictLN_ArtBlockStat_t;
extern G__linked_taginfo G__anacore_dictLN_ArtEventStat_t;
extern G__linked_taginfo G__anacore_dictLN_ArtFileStat_t;
extern G__linked_taginfo G__anacore_dictLN_ArtDataSource_t;
extern G__linked_taginfo G__anacore_dictLN_TArtDataSource;
extern G__linked_taginfo G__anacore_dictLN_TArtRawDataObject;
extern G__linked_taginfo G__anacore_dictLN_TArtRawFADCDataObject;
extern G__linked_taginfo G__anacore_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__anacore_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anacore_dictLN_TArtRawSegmentObject;
extern G__linked_taginfo G__anacore_dictLN_vectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgR;
extern G__linked_taginfo G__anacore_dictLN_reverse_iteratorlEvectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anacore_dictLN_vectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgR;
extern G__linked_taginfo G__anacore_dictLN_reverse_iteratorlEvectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoder;
extern G__linked_taginfo G__anacore_dictLN_TArtDecodercLcLmask_t;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderA3100;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderAD413A;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderAMTTDC;
extern G__linked_taginfo G__anacore_dictLN_Moudle;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderCBLT;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderCTM405;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderDSP;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderFactory;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderFixed16;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderFixed24;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderFixed32;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderL3377d;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderLUPO;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderMADC32;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderP716X;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderP716XZ;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderV1190C;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderV1190;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderV1290;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderV1740;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderV550;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderV767;
extern G__linked_taginfo G__anacore_dictLN_TArtDecoderV7XX;
extern G__linked_taginfo G__anacore_dictLN_TArtEventInfo;
extern G__linked_taginfo G__anacore_dictLN_TArtRawScalerObject;
extern G__linked_taginfo G__anacore_dictLN_TArtRawEventObject;
extern G__linked_taginfo G__anacore_dictLN_vectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgR;
extern G__linked_taginfo G__anacore_dictLN_reverse_iteratorlEvectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anacore_dictLN_vectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgR;
extern G__linked_taginfo G__anacore_dictLN_reverse_iteratorlEvectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anacore_dictLN_TArtParser;
extern G__linked_taginfo G__anacore_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__anacore_dictLN_TTree;
extern G__linked_taginfo G__anacore_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__anacore_dictLN_TArtStoreManager;
extern G__linked_taginfo G__anacore_dictLN_TArtEventStore;
extern G__linked_taginfo G__anacore_dictLN_stat;
extern G__linked_taginfo G__anacore_dictLN_TArtFileDataSource;
extern G__linked_taginfo G__anacore_dictLN_TArtRIDFMap;
extern G__linked_taginfo G__anacore_dictLN_TArtMath;
extern G__linked_taginfo G__anacore_dictLN_TArtParserFactory;
extern G__linked_taginfo G__anacore_dictLN_TArtMapper;
extern G__linked_taginfo G__anacore_dictLN_TArtParserRDF;
extern G__linked_taginfo G__anacore_dictLN_TArtParserRIDF;
extern G__linked_taginfo G__anacore_dictLN_TArtParserRIDFcLcLArtHeader_t;
extern G__linked_taginfo G__anacore_dictLN_TArtParserRIDFcLcLArtSegIDRIDF_t;
extern G__linked_taginfo G__anacore_dictLN_TArtReconstruction;
extern G__linked_taginfo G__anacore_dictLN_TArtSemaphore;
extern G__linked_taginfo G__anacore_dictLN_TArtSemaphorecLcLsembuf;
extern G__linked_taginfo G__anacore_dictLN_TArtSharedMemory;
extern G__linked_taginfo G__anacore_dictLN_TArtSharedMemoryDataSource;
extern G__linked_taginfo G__anacore_dictLN_TSocket;
extern G__linked_taginfo G__anacore_dictLN_TArtStreamingDataSource;
extern G__linked_taginfo G__anacore_dictLN_TArtUtil;

/* STUB derived class for protected member access */
